### ISSUE TITLE
Can't find 'Image as a Reference' code

### ISSUE THREAD

**Issue by Leo1214** [koushiksrivats/face_attribute_attack#2]
Thank you for the code you provided！ But why I didn’t find 'Image as a Reference' code? If you only offer 'Test as a Reference' code?

**Comment by ccu1tn** [comment]
@Leo1214 Have you seen it, bro.?

**Comment by fahadshamshad** [comment]
Hi, we are currently busy with some deadlines. We will upload it in the coming few weeks. Thanks for your patience and understanding.

**Comment by hsien999** [comment]
> Hi, we are currently busy with some deadlines. We will upload it in the coming few weeks. Thanks for your patience and understanding.

When will you make the code for image_as_reference public?

**Comment by koushiksrivats** [comment]
Hi all
Thank you for your interest in our work.
We apologize for the delayed response.

Please note that we have now released the image_as_reference code and the corresponding config file.

Thank You
